import { db } from "./db";
import { indicators } from "@shared/schema";

const seedIndicators = [
  {
    name: "Quantum Trend Pro",
    slug: "quantum-trend-pro",
    shortDescription: "Advanced trend-following algorithm with multi-timeframe confluence detection and dynamic trailing stops.",
    description: "Quantum Trend Pro is a next-generation trend-following indicator built for serious traders who demand precision. Using proprietary multi-timeframe analysis, it identifies high-probability trend continuations while filtering out market noise.\nThe algorithm combines exponential moving average crossovers with volatility-adjusted momentum filters to deliver clean, actionable signals. Unlike traditional trend indicators, Quantum Trend Pro adapts to changing market conditions in real-time, automatically adjusting sensitivity based on current volatility regimes.\nWhether you trade forex, crypto, stocks, or futures, this indicator provides clear entry and exit signals with calculated stop-loss and take-profit levels for every trade setup.",
    category: "Trend Following",
    price: "49",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Multi-timeframe trend confluence engine",
      "Dynamic trailing stop-loss system",
      "Volatility-adjusted signal sensitivity",
      "Auto-calculated TP/SL levels",
      "Works on all markets and timeframes",
      "Real-time push notifications",
    ],
    winRate: "73.2%",
    avgReturn: "+2.8%",
    totalTrades: "1,247",
    trialDays: 7,
  },
  {
    name: "Volume Profile Elite",
    slug: "volume-profile-elite",
    shortDescription: "Institutional-grade volume analysis with point of control, value area, and HVN/LVN detection.",
    description: "Volume Profile Elite reveals where institutional money is positioned by mapping volume distribution across price levels. This is the same methodology used by hedge funds and proprietary trading firms to identify key support, resistance, and fair value zones.\nThe indicator automatically plots the Point of Control (POC), Value Area High (VAH), and Value Area Low (VAL) for any selected range. It also highlights High Volume Nodes (HVN) where price is likely to consolidate and Low Volume Nodes (LVN) where price tends to move quickly.\nUse Volume Profile Elite to understand the story behind price action and make decisions based on where real money has been exchanged.",
    category: "Volume Analysis",
    price: "39",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Automatic POC, VAH, VAL calculation",
      "High/Low Volume Node detection",
      "Session, visible range, and fixed range profiles",
      "Customizable value area percentage",
      "Delta volume integration",
      "Clean, non-cluttered visualization",
    ],
    winRate: "68.5%",
    avgReturn: "+2.1%",
    totalTrades: "982",
    trialDays: 7,
  },
  {
    name: "Smart Money Tracker",
    slug: "smart-money-tracker",
    shortDescription: "Track institutional order flow with order block detection, liquidity sweeps, and fair value gap mapping.",
    description: "Smart Money Tracker is designed for traders who follow the Smart Money Concepts (SMC) methodology. It automates the detection of institutional order blocks, fair value gaps (FVG), and liquidity pools that drive market structure.\nThe indicator identifies where banks and institutions are placing their orders by analyzing market structure breaks, change of character (CHoCH) signals, and break of structure (BOS) events. It marks order blocks that have the highest probability of being revisited and highlights fair value gaps that act as magnets for price.\nCombine this with the built-in liquidity sweep detector to anticipate stop hunts and enter trades where smart money enters.",
    category: "Smart Money",
    price: "59",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Automatic order block detection and grading",
      "Fair value gap mapping with fill tracking",
      "Liquidity pool and sweep detection",
      "Break of Structure (BOS) alerts",
      "Change of Character (CHoCH) signals",
      "Multi-timeframe structure overlay",
    ],
    winRate: "71.8%",
    avgReturn: "+3.4%",
    totalTrades: "856",
    trialDays: 7,
  },
  {
    name: "Momentum Surge",
    slug: "momentum-surge",
    shortDescription: "Catch explosive moves early with RSI divergence detection, momentum oscillator, and exhaustion signals.",
    description: "Momentum Surge identifies the exact moments when momentum is building for explosive price moves. Using a proprietary blend of RSI divergence analysis, MACD histogram patterns, and volume-weighted momentum scoring, it pinpoints high-probability breakout and reversal setups.\nThe indicator features a unique \"Surge Score\" that combines multiple momentum factors into a single, easy-to-read value. When the score crosses key thresholds, it generates clear buy or sell signals with corresponding confidence levels.\nMomentum Surge also includes an exhaustion detector that warns when a trend is losing steam, helping you exit positions before reversals occur.",
    category: "Momentum",
    price: "35",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Proprietary Surge Score algorithm",
      "Multi-factor RSI divergence detection",
      "Momentum exhaustion warnings",
      "Volume-weighted momentum analysis",
      "Breakout anticipation signals",
      "Configurable alert thresholds",
    ],
    winRate: "66.9%",
    avgReturn: "+2.5%",
    totalTrades: "1,534",
    trialDays: 7,
  },
  {
    name: "Volatility Edge",
    slug: "volatility-edge",
    shortDescription: "Master volatility with Bollinger Band squeezes, ATR-based signals, and volatility regime classification.",
    description: "Volatility Edge gives you a complete understanding of market volatility and how to trade it profitably. The indicator classifies the current market into volatility regimes — low, normal, high, and extreme — and adjusts its signals accordingly.\nThe core engine uses a combination of Bollinger Band squeeze detection, ATR breakout signals, and Keltner Channel analysis to identify when volatility is about to expand or contract. This gives you a significant edge in timing your entries for maximum profit potential.\nThe indicator also includes a unique volatility mean-reversion system that identifies when price has stretched too far from its norm and is likely to snap back.",
    category: "Volatility",
    price: "45",
    videoUrl: null,
    imageUrl: null,
    features: [
      "Volatility regime classification system",
      "Bollinger Band squeeze detector",
      "ATR-based breakout signals",
      "Volatility mean-reversion alerts",
      "Keltner Channel integration",
      "Historical volatility comparison",
    ],
    winRate: "70.1%",
    avgReturn: "+2.3%",
    totalTrades: "1,103",
    trialDays: 7,
  },
  {
    name: "Support & Resistance AI",
    slug: "support-resistance-ai",
    shortDescription: "AI-powered key level detection with strength scoring, zone clustering, and historical touch analysis.",
    description: "Support & Resistance AI uses machine learning algorithms to identify the most significant support and resistance levels on any chart. Unlike basic horizontal line tools, this indicator analyzes price action history, volume at price, and institutional footprint data to rank levels by their importance.\nEach level receives a strength score from 1-10 based on how many times price has reacted to it, the volume traded there, and how recently it was tested. The AI engine clusters nearby levels into zones, giving you a cleaner chart while maintaining accuracy.\nThe indicator also tracks level breaks and retests, automatically updating its analysis as market conditions evolve.",
    category: "Support/Resistance",
    price: "42",
    videoUrl: null,
    imageUrl: null,
    features: [
      "AI-powered level detection algorithm",
      "Strength scoring system (1-10 scale)",
      "Automatic zone clustering",
      "Break and retest tracking",
      "Historical touch count analysis",
      "Dynamic level updating",
    ],
    winRate: "69.4%",
    avgReturn: "+2.0%",
    totalTrades: "1,389",
    trialDays: 7,
  },
];

export async function seedDatabase() {
  const existing = await db.select().from(indicators);
  if (existing.length > 0) return;

  for (const ind of seedIndicators) {
    await db.insert(indicators).values(ind);
  }
  console.log("Database seeded with indicators");
}
